<a href=""><img class="logo-footer" src="<?= $this->getViewFileUrl('Magento_Theme::images/img/logo.svg'); ?>" alt="logo"></a>
<div class="footer-section">
    <h5>Occasions</h5>
    <nav>
        <a href="http://magento2.test/occasions.html">Occasions</a>
        <a href="#">Working From Home</a>
        <a href="#">Snack Time</a>
        <a href="#">Breakfast</a>
        <a href="#">Vegan Life</a>
        <a href="#">Baking</a>
        <a href="#">Gifts & Bundles</a>
        <a href="#">Easy Cooking</a>
        <a href="#">All Products</a>
    </nav>
</div>
<div class="footer-section">
    <h5>All Categories</h5>
    <nav>
        <a href="#">Baking</a>
        <a href="#">Breakfast</a>
        <a href="#">Condiments</a>
        <a href="#">Drinks</a>
        <a href="#">Heat Things Up</a>
        <a href="#">Meal Solutions</a>
        <a href="#">Pantry Staples</a>
        <a href="#">Simmer Sauces</a>
        <a href="#">Snacks & Treats</a>
        <a href="#">Spice Up Your Cooking</a>
        <a href="#">Sweet Tooth</a>
        <a href="#">Wine & Cheese</a>
        <a href="#">All Products</a>
    </nav>
</div>
<div class="footer-section">
    <h5>Gifts & Bundles</h5>
    <nav>
        <a href="#">Sweet Tooth Special</a>
        <a href="#">Discover Local</a>
        <a href="#">Baking Box</a>
        <a href="#">Spicy Heat Lover's Box</a>
        <a href="#">Snacking Sensations</a>
    </nav>
</div>
<div class="footer-section ">
    <h5>Our Brands</h5>
</div>
<div class="footer-section ">
    <h5>About Us</h5>
</div>
</footer>
