<div class="top-menu">
    <div class="round">
        <a class="search" href="#search">
            <img class="search" src="<?= $this->getViewFileUrl('Magento_Theme::images/img/search.svg'); ?>" class="search" alt="search">
        </a>
    </div>
    <div class="round">
        <a class="profile" href="#profile">
            <img class="profile" src="<?= $this->getViewFileUrl('Magento_Theme::images/img/profile.svg'); ?>" class="profile" alt="profile">
        </a>
    </div>
</div>








