<section class="inf-sections">
    <div class="section-right">
    </div>
    <div class="section-left">
        <h3>Surprise Someone
            <pre><b>Working from Home</b></pre>
        </h3>
        <p>
            Do you have a colleague or family member working hard at home? Our Working From Home box of snacks
            and drinks is the perfect way to put a smile on their face, delivered direct to their
            door.<br/><br/> To buy for a large group of
            people, get in touch and we can discuss bespoke bundles and personalised messaging.
        </p>
        <button>Buy Now</button>
    </div>
</section>
