<section class="food_info">
    <div class="right">
        <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/right.png'); ?>" alt="grapes">
    </div>
    <div class="left">
        <h3>Who Makes <b>Your Food?</b></h3>
        <p>
            Our mission is to help grow the local food ecosystem in BC and across Canada. Why?
        </p>
        <ul class="list">
            <li>
                Because it connects us to the land we live on, and to the people who live here.
            </li>
            <li>
                Because it’s more meaningful to cook and eat something made by a person nearby than by some
                distant corporation
            </li>
            <li>
                Because good local food makes our corner of the world a better place to live
            </li>
            <li>Because it supports local jobs</li>
            <li>Because it makes more sense for the environment</li>
        </ul>
        <button>Discover our Producers</button>
    </div>
</section>
