<section class="inf-section">
    <h2>
        Why Choose <b>the Premium Bakery Quality</b>
    </h2>
    <div class="wrap-info">
        <div class="info-item">
            <img width="48px" height="48px" src="<?= $this->getViewFileUrl('Magento_Theme::images/img/telescope.svg'); ?>" alt="telescope">
            <h3>Discover new flavours & people</h3>
            <p>
                Discover new tastes, flavours, snacks and recipes to make wonderful meals. Also find out where
                your food comes from and who makes it.
            </p>
        </div>
        <div class="info-item">
            <img width="48px" height="48px"
                 src="<?= $this->getViewFileUrl('Magento_Theme::images/img/wholesale.png'); ?>" alt="wholesale">
            <h3>Buy wholesale</h3>
            <p>
                We offer bulk formats, variety cases, and discovery boxes so you can save money on delicious
                foods by buying at wholesale prices.
            </p>
        </div>
        <div class="info-item">
            <img width="48px" height="48px" src="<?= $this->getViewFileUrl('Magento_Theme::images/img/support.svg'); ?>"
                 alt="support">
            <h3>Support your community</h3>
            <p>
                By buying in bulk from local and Canadian producers you are helping grow our local food
                ecosystem, creating jobs, and supporting families and entrepreneurs in your community.
            </p>
        </div>
        <div class="info-item">
            <img width="48px" height="48px" src="<?= $this->getViewFileUrl('Magento_Theme::images/img/winner.svg'); ?>"
                 alt="winner">
            <h3>Enjoy the best quality</h3>
            <p>
                We only offer great tasting, all natural foods that are better for you, and organic if possible.
            </p>
        </div>
        <div class="info-item">
            <img width="48px" height="48px" src="<?= $this->getViewFileUrl('Magento_Theme::images/img/heart.svg'); ?>"
                 alt="heart">
            <h3>Enjoy Club Level Service</h3>
            <p>
                As a member of our club, we will make sure you are delighted with our service or we will make it
                right!
            </p>
        </div>
</section>
