<section class="bakery_quality">
    <a href="https://www.instagram.com/premium.bakery/">@PremiumBakeryQuality</a>
    <i>on Instagram</i>
    <!-- this here place for slider -->
    <div class="wrap-slider">
        <div class="container">
            <div class="slider">
                <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/1.png'); ?>"
                     alt="slider">
                <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/2.png'); ?>"
                     alt="slider">
                <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/3.png'); ?>"
                     alt="slider">
                <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/4.png'); ?>"
                     alt="slider">
                <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/5.png'); ?>"
                     alt="slider">
            </div>
        </div>
    </div>
</section>

<script type="text/x-magento-init">
    {
        "*": {
            "slider": {
                "wrapper": ".slider"
            }
        }
    }
</script>
