<section class="communication">
    <h4 class="tell-a-friend">Tell a friend</h4>
    <nav class="com-item">
        <a href="#"><img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/facebook.svg'); ?>" alt="facebook"></a>
        <a href="#"> <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/instagram.svg'); ?>" alt="instagram"> </a>
        <a href="#"> <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/twitter.svg'); ?>" alt="twitter"></a>
        <a href="#"> <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/whatsapp.svg'); ?>" alt="whatsapp"></a>
        <a href="#"> <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/messenger.svg'); ?>" alt="facebook"></a>
        <a href="#"> <img src="<?= $this->getViewFileUrl('Magento_Theme::images/img/telegram.svg'); ?>" alt="telegramm"> </a>
    </nav>
</section>
